export enum SuccessStatus {
  SUCCESS = "SUCCESS",
  PASSWORD_SET = "PASSWORD_SET",
  PROCEED = "PROCEED",
  ACCOUNT_CREATED = "ACCOUNT_CREATED",
  EMAIL_SENT = "EMAIL_SENT",
  ADMIN_CREATED = "ADMIN_CREATED",
  VALID_ACCESS_CODE = "VALID_ACCESS_CODE",
  TOKEN_REFRESHED = "TOKEN_REFRESHED",
  LOGGED_OUT = "LOGGED_OUT",
  ADMIN_DELETED = "ADMIN_DELETED",
  OTAC_REFRESHED = "OTAC_REFRESHED",
  ADMIN_RESET = "ADMIN_RESET",
}