export enum SuccessStatus {
  SUCCESS = "SUCCESS",
  PASSWORD_SET = "PASSWORD_SET",
  PROCEED = "PROCEED",
  ACCOUNT_CREATED = "ACCOUNT_CREATED",
  EMAIL_SENT = "EMAIL_SENT",
  ADMIN_CREATED = "ADMIN_CREATED",
  VALID_ACCESS_CODE = "VALID_ACCESS_CODE",
}